spring.application.name=eventticket

server.port=8080

## DB Connection
spring.datasource.url=jdbc:postgresql://localhost:INSERTLOCALHOSTNUMBER/ticketing_db
spring.datasource.username=postgres
spring.datasource.password=insertpasswordhere
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect